### PR TITLE
WIP: Serach for an existing key by fingerprint before attempting upload

### LINKED ISSUE #49: Creating multiple machines with the same SSH key
Hello,

I'm trying to create multiple machines with the same SSH Key. The first machine is created successfully, but the creation fails for the next machines with the following error:

```
Error creating machine: Error in driver during machine creation: could not create ssh key: SSH key with the same fingerprint already exists (uniqueness_error)
```

## How to reproduce

I have an already existent SSH keypair: `/home/am/.ssh/id_rsa` and `/home/am/.ssh/id_rsa.pub`.

I create the first machine with `docker-machine create --driver hetzner --hetzner-api-token $MY_TOKEN --hetzner-existing-key-path /home/am/.ssh/id_rsa machine1`. The machine is created successfully.

I try to create the second machine with `docker-machine create --driver hetzner --hetzner-api-token $MY_TOKEN --hetzner-existing-key-path /home/am/.ssh/id_rsa machine2`. The creation fails

Detailed log: [machine.log](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/files/5349387/machine.log)

### PR DESCRIPTION
**Pull request by am97**
fixes #49

With this fix, the creation of two machines as described in #49 works. The removal is also successful:

```
am@localhost:~/go/src/github.com/am97/docker-machine-driver-hetzner$ docker-machine rm machine1
About to remove machine1
WARNING: This action will delete both local reference and remote instance.
Are you sure? (y/n): y
(machine1)  -> Destroying server machine1[7976813] in...
(machine1)  -> Destroying SSHKey am@am[2167977]...
Successfully removed machine1
am@localhost:~/go/src/github.com/am97/docker-machine-driver-hetzner$ docker-machine rm machine2
About to remove machine2
WARNING: This action will delete both local reference and remote instance.
Are you sure? (y/n): y
(machine2)  -> Destroying server machine2[7976887] in...
(machine2)  -> SSH key does not exist anymore
Successfully removed machine2
```

### CODE REVIEW

File: driver.go [hunk 1]
```diff
@@ -241,14 +241,29 @@ func (d *Driver) Create() error {
 			return errors.Wrap(err, "could not read ssh public key")
 		}
 
-		keyopts := hcloud.SSHKeyCreateOpts{
-			Name:      d.GetMachineName(),
-			PublicKey: string(buf),
+		// Try to find a key with the same Fingerprint
```
Comment (JonasProgrammer) [inline driver.go:244]: In general: given the amount of logic here, I'd almost opt to put this in a separate function

File: driver.go [hunk 2]
```diff
@@ -241,14 +241,29 @@ func (d *Driver) Create() error {
...
+		pubkey, _, _, _, err := ssh.ParseAuthorizedKey(buf)
+		if err != nil {
+			return errors.Wrap(err, "could not parse ssh public key")
 		}
 
-		key, _, err := d.getClient().SSHKey.Create(context.Background(), keyopts)
+		fp := ssh.FingerprintLegacyMD5(pubkey)
+
+		key, _, err := d.getClient().SSHKey.GetByFingerprint(context.Background(), fp)
 		if err != nil {
```
Comment (JonasProgrammer) [inline driver.go:253]: Did you get key and err mixed up here?

File: driver.go [hunk 3]
```diff
@@ -241,14 +241,29 @@ func (d *Driver) Create() error {
...
-			return errors.Wrap(err, "could not create ssh key")
+			log.Debugf("SSH key not found in Hetzner. Uploading...")
```
Comment (JonasProgrammer) [inline driver.go:254]: Personally I think that this is actually useful information for normal users, as you should refrain from altering auto-uploaded keys manually instead of using `docker-machine`.
So I'd opt to use `Infof` instead of `Debugf` here.

File: driver.go (hunk 2 above)
Comment (am97) [reply driver.go:253]: You are right, the condition should be `if key == nil`

**Comment by am97** [comment]
Thanks for your feedback. I moved some logic to `getRemoteKeyWithSameFingerprint()` (the name is a bit long, but I don't have other ideas), fixed the condition and replaced `log.Debugf` with `log.Infof` to inform users that SSH key is 
being uploaded.

Feel free to edit the PR if you want :)

**Review by JonasProgrammer — APPROVED** [review]
LGTM
